<a href="https://colab.research.google.com/github/SaurabhSRP/POC-NLP-conceptProjects/blob/main/NLP_Fake_news_classifier_using_ML_algo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


In [4]:
test=pd.read_csv("https://raw.githubusercontent.com/SaurabhSRP/POC-NLP-conceptProjects/main/fake-news/test.csv")
test.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [6]:
submit=pd.read_csv("https://raw.githubusercontent.com/SaurabhSRP/POC-NLP-conceptProjects/main/fake-news/submit.csv")
submit.head()

id  label
0  20800      0
1  20801      1
2  20802      0
3  20803      1
4  20804      1

In [8]:
df=pd.merge(test,submit,on="id")
df.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  \
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...   
1                      NaN  Russian warships ready to strike terrorists ne...   
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...   
3            Daniel Victor  If at first you don’t succeed, try a different...   
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...   

   label  
0      0  
1      1  
2      0  
3      1  
4      1

In [10]:
##Get the independent Feature
X=df.drop('label',axis=1)
X.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [12]:
###Get dependent feature
y=df['label']
y.head()

0    0
1    1
2    0
3    1
4    1
Name: label, dtype: int64

#**Text preprocessing** - We will try three different vectorizers 

In [13]:
df=df.dropna()

In [14]:
messages=df.copy()

In [15]:
messages.reset_index(inplace=True) #after dropping nan values , some of the indexes will be dropped 

In [21]:
messages.head() ##there is some difference and missing number in our indexing

index     id                                              title  \
0      0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1      2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
2      3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
3      4  20804                    Keiser Report: Meme Wars (E995)   
4      6  20806  Pelosi Calls for FBI Investigation to Find Out...   

                    author                                               text  \
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...   
1            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...   
2            Daniel Victor  If at first you don’t succeed, try a different...   
3  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...   
4                  Pam Key  Sunday on NBC’s “Meet the Press,” House Minori...   

   label  
0      0  
1      0  
2      1  
3      1  
4      1

In [20]:
messages['title'][3]

'Keiser Report: Meme Wars (E995)'

In [28]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [29]:
corpus=[]
for i in range(0,len(messages)):
  review=re.sub('[^a-zA-Z]',' ',messages['title'][i])
  review=review.lower()
  review=review.split()

  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)
  #corpus has only messages - title feature

#**CountVectorizer**

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,ngram_range=(1,3))
X=cv.fit_transform(corpus).toarray()

In [34]:
X.shape

(4575, 5000)

In [35]:
y=messages['label']

In [37]:
##divide the dataset into train and test 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=10)

In [38]:
cv.get_feature_names()[:20] ##feature names among the 5000 features

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['aaron',
 'abandon',
 'abba',
 'abbi',
 'abbi martin',
 'abbi martin expos',
 'abc',
 'abe',
 'abedin',
 'abedin email',
 'abolish',
 'abort',
 'abram',
 'abroad',
 'abroad new',
 'abroad new york',
 'absolut',
 'abus',
 'academi',
 'accept']

In [39]:
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [41]:
count_df=pd.DataFrame(X_train,columns=cv.get_feature_names())
count_df.head() 
#to visulaise our X data

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


aaron  abandon  abba  abbi  abbi martin  abbi martin expos  abc  abe  \
0      0        0     0     0            0                  0    0    0   
1      0        0     0     0            0                  0    0    0   
2      0        0     0     0            0                  0    0    0   
3      0        0     0     0            0                  0    0    0   
4      0        0     0     0            0                  0    0    0   

   abedin  abedin email  ...  york new  york new york  york time  young  \
0       0             0  ...         0              0          1      0   
1       0             0  ...         0              0          0      0   
2       0             0  ...         0              0          0      0   
3       0             0  ...         0              0          0      0   
4       0             0  ...         0              0          1      0   

   youth  youtub  zika  zika viru  zone  zuckerberg  
0      0       0     0          0     0           0  
1      0       0     0          0     0           0  
2      0       0     0          0     0           0  
3      0       0     0          0     0           0  
4      0       0     0          0     0           0  

[5 rows x 5000 columns]

#**MultinomialNB Algo for CountVectorizer**

In [42]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()

In [44]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [45]:
classifier.fit(X_train,y_train)
pred=classifier.predict(X_test)
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))

0.752317880794702
[[525 229]
 [145 611]]


#**MultinomialNB Algo with hyperparameter for CountVectorizer**

In [50]:
classifier=MultinomialNB(alpha=0.1)

In [53]:
previous_score=0
for alpha in np.arange(0,1,0.1):
  sub_classifier=MultinomialNB(alpha=alpha)
  sub_classifier.fit(X_train,y_train)
  y_pred=sub_classifier.predict(X_test)
  score=accuracy_score(y_test,y_pred)
  if score>previous_score:
    classifier=sub_classifier
  print("Alpha: {}, score: {}".format(alpha,score))

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:557: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  % _ALPHA_MIN


Alpha: 0.0, score: 0.6854304635761589
Alpha: 0.1, score: 0.7350993377483444
Alpha: 0.2, score: 0.7417218543046358
Alpha: 0.30000000000000004, score: 0.7450331125827815
Alpha: 0.4, score: 0.7536423841059603
Alpha: 0.5, score: 0.7529801324503311
Alpha: 0.6000000000000001, score: 0.7562913907284768
Alpha: 0.7000000000000001, score: 0.7562913907284768
Alpha: 0.8, score: 0.7556291390728477
Alpha: 0.9, score: 0.7556291390728477


#**Passive Aggressive Classifier Algorithm for CountVecotorizer**

In [48]:
from sklearn.linear_model import PassiveAggressiveClassifier
linear_clf=PassiveAggressiveClassifier()

In [49]:
linear_clf.fit(X_train,y_train)
pred=linear_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))

0.6821192052980133
[[501 253]
 [227 529]]


#**HashingVectorizer**

In [55]:
from sklearn.feature_extraction.text import HashingVectorizer

In [63]:
hs_vectorizer=HashingVectorizer(n_features=5000)
X=hs_vectorizer.fit_transform(corpus).toarray()

In [59]:
X.shape

(4575, 5000)

In [60]:
## Divide the dataset into Train and Test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [64]:
classifier.fit(X_train,y_train)
pred=classifier.predict(X_test)
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))

ValueError: ignored

#**Method to find most fake and most real words**

In [65]:
classifier.coef_[0]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:103: FutureWarning: Attribute `coef_` was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26).
  warnings.warn(msg, category=FutureWarning)


array([-8.76416102, -8.76416102, -8.76416102, ..., -9.93423227,
       -9.93423227, -8.76416102])

In [67]:
feature_names=cv.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [68]:
##Most Real
sorted(zip(classifier.coef_[0],feature_names),reverse=True)[:20]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:103: FutureWarning: Attribute `coef_` was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26).
  warnings.warn(msg, category=FutureWarning)


[(-3.968370476566168, 'breitbart'),
 (-4.089400442090629, 'trump'),
 (-4.449435341322508, 'new'),
 (-4.541109906546817, 'time'),
 (-4.664657377130781, 'york'),
 (-4.664657377130781, 'new york'),
 (-4.705503195071842, 'york time'),
 (-4.705503195071842, 'new york time'),
 (-5.185442861050156, 'hillari'),
 (-5.255192240258617, 'clinton'),
 (-5.656024135445293, 'video'),
 (-5.687325595448942, 'elect'),
 (-5.7530306684977965, 'report'),
 (-5.841741281240386, 'obama'),
 (-5.939094362674511, 'say'),
 (-6.002406642088838, 'us'),
 (-6.069999933221366, 'news'),
 (-6.069999933221366, 'donald'),
 (-6.093585932227246, 'watch'),
 (-6.117741696106581, 'email')]

In [69]:
### Most fake
sorted(zip(classifier.coef_[0], feature_names))[:20]

[(-9.934232274813164, 'abe'),
 (-9.934232274813164, 'adam'),
 (-9.934232274813164, 'adapt'),
 (-9.934232274813164, 'addict'),
 (-9.934232274813164, 'admir endors'),
 (-9.934232274813164, 'admir endors trump'),
 (-9.934232274813164, 'admit key'),
 (-9.934232274813164, 'admit key al'),
 (-9.934232274813164, 'adult'),
 (-9.934232274813164, 'advertis'),
 (-9.934232274813164, 'advoc'),
 (-9.934232274813164, 'afford'),
 (-9.934232274813164, 'afford care'),
 (-9.934232274813164, 'afford care act'),
 (-9.934232274813164, 'age trump'),
 (-9.934232274813164, 'agenda new'),
 (-9.934232274813164, 'agenda new york'),
 (-9.934232274813164, 'ail'),
 (-9.934232274813164, 'airbag'),
 (-9.934232274813164, 'airbag new')]

#**TFidf Vectorizer**

In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [81]:
tfidf_v=TfidfVectorizer(max_features=5000,ngram_range=(1,3))
X=tfidf_v.fit_transform(corpus).toarray()

In [83]:
X.shape

(4575, 5000)

In [84]:
y=messages['label']

In [85]:
##Divide the dataset into train and test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=12)

In [86]:
tfidf_v.get_feature_names()[:20]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['aaron',
 'abandon',
 'abba',
 'abbi',
 'abbi martin',
 'abbi martin expos',
 'abc',
 'abe',
 'abedin',
 'abedin email',
 'abolish',
 'abort',
 'abram',
 'abroad',
 'abroad new',
 'abroad new york',
 'absolut',
 'abus',
 'academi',
 'accept']

In [87]:

tfidf_v.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': None,
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}

In [88]:
count_df = pd.DataFrame(X_train, columns=tfidf_v.get_feature_names())

In [89]:

count_df.head()

aaron  abandon  abba  abbi  abbi martin  abbi martin expos  abc  abe  \
0    0.0      0.0   0.0   0.0          0.0                0.0  0.0  0.0   
1    0.0      0.0   0.0   0.0          0.0                0.0  0.0  0.0   
2    0.0      0.0   0.0   0.0          0.0                0.0  0.0  0.0   
3    0.0      0.0   0.0   0.0          0.0                0.0  0.0  0.0   
4    0.0      0.0   0.0   0.0          0.0                0.0  0.0  0.0   

   abedin  abedin email  ...  york new  york new york  york time  young  \
0     0.0           0.0  ...       0.0            0.0   0.093373    0.0   
1     0.0           0.0  ...       0.0            0.0   0.129376    0.0   
2     0.0           0.0  ...       0.0            0.0   0.000000    0.0   
3     0.0           0.0  ...       0.0            0.0   0.000000    0.0   
4     0.0           0.0  ...       0.0            0.0   0.000000    0.0   

   youth  youtub  zika  zika viru  zone  zuckerberg  
0    0.0     0.0   0.0        0.0   0.0         0.0  
1    0.0     0.0   0.0        0.0   0.0         0.0  
2    0.0     0.0   0.0        0.0   0.0         0.0  
3    0.0     0.0   0.0        0.0   0.0         0.0  
4    0.0     0.0   0.0        0.0   0.0         0.0  

[5 rows x 5000 columns]

In [90]:
classifier.fit(X_train,y_train)
pred=classifier.predict(X_test)
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))

0.7245033112582782
[[514 204]
 [212 580]]
